---
- name: get keyinfo for all keys
  gpg_key:
    homedir: "{{ gpg2_basedir }}"
    fpr: '*'
    state: info
  register: key_dict_to_delete

- name: Delete keys
  gpg_key: 
    fpr: "{{ item.key }}"
    state: absent
  with_items: "{{ key_dict_to_delete['keys'] | dict2items }}"

