---
- name: get keyinfo for all keys
  gpg_key:
    homedir: "{{ gpg2_basedir }}"
    fpr: '*'
    state: info
  register: key_list_to_delete

- name: Delete all keys
  gpg_key: 
    fpr: "{{ item.fingerprint }}"
    state: absent
    whith_items: "{{ key_list_to_delete.keys }}"
