---
# tasks file for ansible-role-gpg2

- include: setup.yml

- include: configure.yml

- include: install.yml
  when: gpg2_install_key_files | length

- include: info.yml
  when: gpg2_show_keys_info | bool