---
# tasks file for ansible-role-gpg2

- include: install.yml

- name: Ensure "{{ gpg2_basedir }}" config directory exists with right permissions
  become: true
  become_user: "{{ gpg2_user }}"
  file:
    dest: "{{ gpg2_basedir }}"
    state: directory
    mode: 0700

- name: Copy over gpg.conf file
  become: true
  become_user: "{{ gpg2_user }}"
  template:
    src : 'gpg.conf.j2'
    dest: '{{ gpg2_basedir }}/gpg.conf'
    owner: "{{ gpg2_user }}"
    group: "{{ gpg2_user }}"
    mode: 0600

- name: get keyinfo for all keys
  gpg_key:
    homedir: "{{ gpg2_basedir }}"
    fpr: '*'
    state: info
  register: key_list

- name: Key List
  debug:
    msg: "{{ key_list }}"