---
# tasks file for ansible-role-gpg2

- include: setup.yml

- include: configure.yml

- include: clean.yml

- include: install.yml

- name: get keyinfo for all keys
  gpg_key:
    homedir: "{{ gpg2_basedir }}"
    fpr: '*'
    state: info
  register: key_list

- name: Key List
  debug:
    msg: "{{ key_list }}"