---
- name: Side Effect
  hosts: all
  gather_facts: false

  vars:
    - gpg_key_basedir: '.gnupg'

  tasks:
  - name:  Side effect - Remove basedir
    file:
      dest: "~/{{ gpg_key_basedir }}"
      state: absent