---

- name: 'Verify'
  hosts: all
  gather_facts: false
  vars:
    test_keys_fpr:
      - 775FDF16E8886A5E0F205C783E2ED0018998A414
      - A885FFC1E7ABD42FD1765054D114C667FB073D89
  tasks:
  - name: get secret key info
    gpg_key:
      fpr: '*'
      state: info
    register: keys_info

  - name: Verify keys are already installed  
    assert:
      that: "{{ item in keys_info['keys'].keys() }}"
    with_items:
      - "{{ test_keys_fpr }}"
